// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinariaAPI.Models;

#nullable disable

namespace VeterinariaAPI.Migrations
{
    [DbContext(typeof(VeterinariaContext))]
    partial class VeterinariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeterinariaAPI.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("VeterinarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Cita__3214EC0725EBD7D5");

                    b.HasIndex("MascotaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("Cita", (string)null);
                });

            modelBuilder.Entity("VeterinariaAPI.Models.DetalleProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__DetalleP__3214EC07AE170BE9");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleProducto");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.HistorialMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CitaId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tratamiento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Historia__3214EC07C58AFE67");

                    b.HasIndex("CitaId");

                    b.HasIndex("MascotaId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("HistorialMedico");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PropietarioId")
                        .HasColumnType("int");

                    b.Property<string>("Raza")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Mascota__3214EC0762E5B8DC");

                    b.HasIndex("PropietarioId");

                    b.ToTable("Mascota", (string)null);
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Persona__3214EC079D5DD214");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Producto__3214EC074B503527");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Usuario__3214EC07F6C601EB");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Cita", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Mascota", "Mascota")
                        .WithMany("Cita")
                        .HasForeignKey("MascotaId")
                        .IsRequired()
                        .HasConstraintName("FK__Cita__MascotaId__3E52440B");

                    b.HasOne("VeterinariaAPI.Models.Usuario", "Usuario")
                        .WithMany("Cita")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Cita__UsuarioId__3F466844");

                    b.HasOne("VeterinariaAPI.Models.Persona", "Veterinario")
                        .WithMany("Cita")
                        .HasForeignKey("VeterinarioId")
                        .HasConstraintName("FK__Cita__Veterinari__403A8C7D");

                    b.Navigation("Mascota");

                    b.Navigation("Usuario");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.DetalleProducto", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Producto", "Producto")
                        .WithMany("DetalleProductos")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__DetallePr__Produ__49C3F6B7");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.HistorialMedico", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Cita", "Cita")
                        .WithMany("HistorialMedicos")
                        .HasForeignKey("CitaId")
                        .HasConstraintName("FK__Historial__CitaI__440B1D61");

                    b.HasOne("VeterinariaAPI.Models.Mascota", "Mascota")
                        .WithMany("HistorialMedicos")
                        .HasForeignKey("MascotaId")
                        .IsRequired()
                        .HasConstraintName("FK__Historial__Masco__4316F928");

                    b.HasOne("VeterinariaAPI.Models.Persona", "Veterinario")
                        .WithMany("HistorialMedicos")
                        .HasForeignKey("VeterinarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Historial__Veter__44FF419A");

                    b.Navigation("Cita");

                    b.Navigation("Mascota");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Mascota", b =>
                {
                    b.HasOne("VeterinariaAPI.Models.Persona", "Propietario")
                        .WithMany("Mascota")
                        .HasForeignKey("PropietarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Mascota__Propiet__3B75D760");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Cita", b =>
                {
                    b.Navigation("HistorialMedicos");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Mascota", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("HistorialMedicos");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Persona", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("HistorialMedicos");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Producto", b =>
                {
                    b.Navigation("DetalleProductos");
                });

            modelBuilder.Entity("VeterinariaAPI.Models.Usuario", b =>
                {
                    b.Navigation("Cita");
                });
#pragma warning restore 612, 618
        }
    }
}
